/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { PasswordService } from "../../auth/password.service";
import { transformStringFieldUpdateInput } from "../../prisma.util";

export class UserServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly passwordService: PasswordService
  ) {}

  async count(args: any): Promise<any> {
    return this.prisma.user.count(args);
  }

  async findMany(args: any): Promise<any[]>{
    return this.prisma.user.findMany(args);
  }
  async findOne(args: any): Promise<any | null> {
    return this.prisma.user.findUnique(args);
  }
  async create(args: any): Promise<any> {
    return this.prisma.user.create(args);
  }
  async update(args: any): Promise<any> {
    return this.prisma.user.update(args);
  }
  async delete(args: any): Promise<any> {
    return this.prisma.user.delete(args);
  }
}
