/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

export class IngredientServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: any): Promise<number> {
    return this.prisma.ingredient.count(args);
  }

  async findMany(args: any): Promise<any[]> {
    return this.prisma.ingredient.findMany(args);
  }
  async findOne(args: any): Promise<any | null> {
    return this.prisma.ingredient.findUnique(args);
  }
  async create(args: any): Promise<any> {
    return this.prisma.ingredient.create(args);
  }
  async update(args: any): Promise<any> {
    return this.prisma.ingredient.update(args);
  }
  async delete(args: any): Promise<any> {
    return this.prisma.ingredient.delete(args);
  }
}
